#!/bin/bash
# env.sh


#next lines generated by AI
# get the directory where this script is located
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# install Q1 python dependencies
pip install scikit-learn numpy matplotlib

# compile Q2 C++ code with O3 optimization
g++ -O3 -Wall -std=c++17 -march=native "$DIR/q2/forest_fire.cpp" -o "$DIR/q2/forest_fire"