#!/bin/bash
# forest_fire.sh
# Usage: bash forest_fire.sh <absolute_path_to_graph> <absolute_path_to_seed_set> <absolute_output_file_path> <k> <n_random_instances> <hops>

#next lines generated by AI

GRAPH_PATH=$1
SEED_PATH=$2
OUT_PATH=$3
K=$4
SIMS=$5
HOPS=$6


DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

"$DIR/forest_fire" "$GRAPH_PATH" "$SEED_PATH" "$OUT_PATH" "$K" "$SIMS" "$HOPS"
