
#include <iostream>
#include <vector>
#include <fstream>
#include <sstream>
#include <unordered_set>
#include <unordered_map>
#include <random>
#include <algorithm>
#include <string>
#include <chrono>
//next lines are generated by AI

using namespace std;

// --- data structures for forest fire blaze paradigm ---

// ek single rasta jahan se aag phail sakti hai
struct BlazeRoute {
    int origin_zone, target_zone;
    float spread_probability;
    int route_id;
};

// piche ki taraf se aag aane ka source (reverse edge)
struct EmberSource {
    int origin_idx;
    float spread_probability;
    int route_id;
};

// poore jungle ka map aur graph structure
struct ForestTerrain {
    unordered_map<int, int> cluster_to_blaze_idx;
    vector<int> blaze_idx_to_cluster;
    vector<vector<EmberSource>> reverse_blaze_paths;
    vector<BlazeRoute> all_blaze_routes;
    int total_routes_count = 0;

    // node ka index dhoondho ya naya assign karo
    int fetch_or_assign_blaze_idx(int zone) {
        auto it = cluster_to_blaze_idx.find(zone);
        if (it != cluster_to_blaze_idx.end()) return it->second;
        
        int new_idx = blaze_idx_to_cluster.size();
        cluster_to_blaze_idx[zone] = new_idx;
        blaze_idx_to_cluster.push_back(zone);
        return new_idx;
    }

    // graph mein naya rasta (edge) jodo
    void map_blaze_route(int u, int v, float prob) {
        int u_idx = fetch_or_assign_blaze_idx(u);
        int v_idx = fetch_or_assign_blaze_idx(v);
        
        int n_req = max(u_idx, v_idx) + 1;
        if ((int)reverse_blaze_paths.size() < n_req) {
            reverse_blaze_paths.resize(n_req * 1.5);
        }
        
        reverse_blaze_paths[v_idx].push_back({u_idx, prob, total_routes_count});
        all_blaze_routes.push_back({u, v, prob, total_routes_count});
        total_routes_count++;
    }

    int total_zones() const { return blaze_idx_to_cluster.size(); }
};

// --- helper functions ---

// file se jungle ka graph load karne ke liye
ForestTerrain parse_forest_terrain(const string& filepath) {
    ForestTerrain terrain;
    ifstream file(filepath);
    string line;
    
    while (getline(file, line)) {
        if (line.empty() || line[0] == '#') continue;
        stringstream ss(line);
        int u, v;
        float prob = 0.5f; // default probability
        
        if (ss >> u >> v) {
            float temp_prob;
            if (ss >> temp_prob) prob = temp_prob;
            terrain.map_blaze_route(u, v, prob);
        }
    }
    
    // memory ko optimize kar rahe hain taaki limit cross na ho
    if ((int)terrain.reverse_blaze_paths.size() < terrain.total_zones()) {
        terrain.reverse_blaze_paths.resize(terrain.total_zones());
    }
    terrain.reverse_blaze_paths.shrink_to_fit();
    for (auto& adj : terrain.reverse_blaze_paths) adj.shrink_to_fit();
    terrain.all_blaze_routes.shrink_to_fit();
    
    return terrain;
}

// shuruwat mein aag kahan lagi hai (seed set) usko read karo
unordered_set<int> identify_initial_blazes(const string& filepath, const ForestTerrain& terrain) {
    unordered_set<int> initial_blaze_zones;
    ifstream file(filepath);
    string line;
    
    while (getline(file, line)) {
        if (line.empty() || line[0] == '#') continue;
        stringstream ss(line);
        int seed_zone;
        if (ss >> seed_zone && terrain.cluster_to_blaze_idx.count(seed_zone)) {
            initial_blaze_zones.insert(terrain.cluster_to_blaze_idx.at(seed_zone));
        }
    }
    return initial_blaze_zones;
}

// greedy approach se sabse zaruri raaste block karo
void deploy_firebreaks(int budget_k, const string& output_filepath, const ForestTerrain& terrain,
                       const unordered_set<int>& initial_blaze_zones,
                       vector<vector<int>>& route_impact_scores,
                       const vector<vector<int>>& simulated_blaze_scenarios,
                       int total_scenarios_generated) {
    
    vector<int> current_impact(terrain.total_routes_count, 0);
    vector<bool> route_blocked(terrain.total_routes_count, false);
    
    // har route ka initial impact score set karo
    for (int route_id = 0; route_id < terrain.total_routes_count; ++route_id) {
        int target_idx = terrain.cluster_to_blaze_idx.at(terrain.all_blaze_routes[route_id].target_zone);
        
        // agar rasta seed ki taraf ja raha hai toh usko block karne ka koi fayda nahi
        if (initial_blaze_zones.count(target_idx)) {
            current_impact[route_id] = -1;
            route_blocked[route_id] = true;
        } else {
            current_impact[route_id] = route_impact_scores[route_id].size();
        }
    }
    
    vector<bool> scenario_covered(total_scenarios_generated, false);
    vector<int> final_firebreaks;
    ofstream out_file(output_filepath);
    
    // k raaste block karne ka loop
    for (int step = 0; step < budget_k; ++step) {
        int optimal_route = -1;
        int max_impact = -1;
        
        for (int route_id = 0; route_id < terrain.total_routes_count; ++route_id) {
            if (!route_blocked[route_id] && current_impact[route_id] > max_impact) {
                max_impact = current_impact[route_id];
                optimal_route = route_id;
            }
        }
        
        if (max_impact <= 0 || optimal_route == -1) break;
        
        final_firebreaks.push_back(optimal_route);
        route_blocked[optimal_route] = true;
        
        // jab ek rasta block kiya, toh uske covered scenarios ko update karo
        for (int scenario_id : route_impact_scores[optimal_route]) {
            if (!scenario_covered[scenario_id]) {
                scenario_covered[scenario_id] = true;
                for (int affected_route : simulated_blaze_scenarios[scenario_id]) {
                    if (!route_blocked[affected_route] && current_impact[affected_route] > 0) {
                        current_impact[affected_route]--;
                    }
                }
            }
        }
        
        out_file << terrain.all_blaze_routes[optimal_route].origin_zone << " " 
                 << terrain.all_blaze_routes[optimal_route].target_zone << "\n";
    }
    
    // agar budget bach gaya aur koi achha rasta nahi mila toh koi bhi bacha hua block kar do
    for (int route_id = 0; route_id < terrain.total_routes_count && final_firebreaks.size() < (size_t)budget_k; ++route_id) {
        if (!route_blocked[route_id]) {
            final_firebreaks.push_back(route_id);
            route_blocked[route_id] = true;
            out_file << terrain.all_blaze_routes[route_id].origin_zone << " " 
                     << terrain.all_blaze_routes[route_id].target_zone << "\n";
        }
    }
}

// --- main execution logic ---

int main(int argc, char* argv[]) {
    if (argc != 7) {
        cerr << "Usage: ./forest_fire <graph> <seeds> <out> <k> <sims> <hops>\n";
        return 1;
    }
    
    string graph_path = argv[1];
    string seed_path = argv[2];
    string output_path = argv[3];
    int budget_k = stoi(argv[4]);
    int n_random_instances = stoi(argv[5]);
    int max_hops = stoi(argv[6]);
    
    // 1. data load karo
    ForestTerrain terrain = parse_forest_terrain(graph_path);
    unordered_set<int> initial_blaze_zones = identify_initial_blazes(seed_path, terrain);
    
    // 2. reverse reachable (rr) sets setup karo
    int target_scenarios = max(50000, n_random_instances * 500);
    vector<vector<int>> route_impact_scores(terrain.total_routes_count);
    vector<vector<int>> simulated_blaze_scenarios;
    simulated_blaze_scenarios.reserve(target_scenarios);
    
    int valid_scenarios_count = 0;
    mt19937 rng(42);
    uniform_int_distribution<int> unif_zone(0, terrain.total_zones() - 1);
    uniform_real_distribution<float> unif_prob(0.0f, 1.0f);
    
    vector<int> blaze_distance(terrain.total_zones(), -1);
    vector<int> search_queue;
    search_queue.reserve(terrain.total_zones());
    
    auto time_start = chrono::high_resolution_clock::now();
    
    // 3. random scenarios generate karo (simulate fire paths)
    for (int i = 0; i < target_scenarios; ++i) {
        if (i > 0 && i % 5000 == 0) {
            auto duration = chrono::duration_cast<chrono::milliseconds>(chrono::high_resolution_clock::now() - time_start);
            cout << "Generated " << i << " scenarios in " << duration.count() << " ms.\n";
        }
        
        int start_zone = unif_zone(rng);
        search_queue.clear();
        search_queue.push_back(start_zone);
        blaze_distance[start_zone] = 0;
        
        int q_head = 0;
        vector<int> paths_taken;
        vector<int> explored_zones = {start_zone};
        bool hit_initial_blaze = false;
        
        // bfs se piche ki taraf jao taaki path mil sake
        while (q_head < (int)search_queue.size()) {
            int current_zone = search_queue[q_head++];
            int dist = blaze_distance[current_zone];
            
            // agar aag ke source tak pahunch gaye, toh rasta mil gaya
            if (initial_blaze_zones.count(current_zone)) {
                hit_initial_blaze = true;
                continue;
            }
            
            // agar hop limit cross ho gayi toh aage mat badho
            if (max_hops != -1 && dist >= max_hops) continue;
            
            for (const auto& ember : terrain.reverse_blaze_paths[current_zone]) {
                // probability ke hisaab se check karo ki aag phail sakti thi ya nahi
                if (unif_prob(rng) <= ember.spread_probability) {
                    paths_taken.push_back(ember.route_id);
                    if (blaze_distance[ember.origin_idx] == -1) {
                        blaze_distance[ember.origin_idx] = dist + 1;
                        search_queue.push_back(ember.origin_idx);
                        explored_zones.push_back(ember.origin_idx);
                    }
                }
            }
        }
        
        // agar seed tak connect hua toh is scenario ko record kar lo
        if (hit_initial_blaze) {
            sort(paths_taken.begin(), paths_taken.end());
            paths_taken.erase(unique(paths_taken.begin(), paths_taken.end()), paths_taken.end());
            
            simulated_blaze_scenarios.push_back(std::move(paths_taken));            
            for (int route_id : simulated_blaze_scenarios.back()) {
                route_impact_scores[route_id].push_back(valid_scenarios_count);
            }
            valid_scenarios_count++;
        }
        
        // state clean karo aagle simulation ke liye
        for (int v : explored_zones) blaze_distance[v] = -1;
    }
    
    // final selection se pehle memory saaf karo
    for (int route_id = 0; route_id < terrain.total_routes_count; ++route_id) {
        route_impact_scores[route_id].shrink_to_fit();
    }
    simulated_blaze_scenarios.shrink_to_fit();
    
    // 4. best routes select karke output file mein likho
    deploy_firebreaks(budget_k, output_path, terrain, initial_blaze_zones, 
                      route_impact_scores, simulated_blaze_scenarios, valid_scenarios_count);
                      
    return 0;
}
// }