import sys
import urllib.request
import json
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
import warnings
warnings.filterwarnings("ignore")

#next lines are generated by AI

mera_roll = "cs5120272"

def api_se_data_lao(dataset_id):
    # api se dataset download karne ka function
    api_link = f"http://hulk.cse.iitd.ac.in:3000/dataset?student_id={mera_roll}&dataset_num={dataset_id}"
    
    try:
        with urllib.request.urlopen(api_link) as reply:
            ro_text = reply.read().decode('utf-8')
            pared_jason = json.loads(ro_text)
            return np.array(pared_jason["X"])
    except Exception as gadbad:
        print(f"json parse eror dataset {dataset_id}:", gadbad)
        sys.exit(1)

def kmeans_test_chalao(input_points):
    # k = 1 se 15 tak inertia aur silhouette evaluate karna
    
    possible_k = range(1, 16)
    
    inertia_list = []
    silllhouette_map = {}
    
    for current_k in possible_k:
        cluster_machine = KMeans(n_clusters=current_k, n_init=10, random_state=42)
        preddiicted_labels = cluster_machine.fit_predict(input_points)
        
        inertia_list.append(cluster_machine.inertia_)
        
        # silhouette score tabhi valid hai jab clusters >=2
        if current_k > 1:
            sil_val = silhouette_score(input_points, preddiicted_labels)
            silllhouette_map[current_k] = sil_val
    
    # best k silhouette max se select
    best_cluster_count = max(silllhouette_map.keys(), key=lambda k: silllhouette_map[k])
    
    return list(possible_k), inertia_list, best_cluster_count

def main():
    
    # argument check
    if len(sys.argv) < 2:
        print("usage:")
        print(" python3 Q1.py <dataset_num>")
        print(" python3 Q1.py <dataset_file>.npy")
        sys.exit(1)
        
    user_input = sys.argv[1]
    
    if user_input.endswith('.npy'):
        # mode 2: local npy file load
        
        data_matrix = np.load(user_input)
        
        k_values, inertia_values, best_k = kmeans_test_chalao(data_matrix)
        
        fig_obj, axis_obj = plt.subplots(1, 1, figsize=(8, 6))
        
        axis_obj.plot(k_values, inertia_values, marker='o', linestyle='-', color='b')
        axis_obj.axvline(x=best_k, color='r', linestyle='--',
                         label=f'optimal k={best_k} (silhouette)')
        
        axis_obj.set_title(f"dataset from {user_input} - kmeans objective")
        axis_obj.set_xlabel("number of clusters (k)")
        axis_obj.set_ylabel("objective value (inertia)")
        
        axis_obj.legend()
        axis_obj.grid(True, linestyle='--', alpha=0.6)
        
        plt.tight_layout()
        plt.savefig('plot.png')
        
        print(best_k)
        
    else:
        # mode 1: api dataset
        
        target_dataset = user_input
        
        # piazza instruction: dono dataset fetch karke plot banana
        
        dataset_one = api_se_data_lao(1)
        dataset_two = api_se_data_lao(2)
        
        k1, inertia1, best_k1 = kmeans_test_chalao(dataset_one)
        k2, inertia2, best_k2 = kmeans_test_chalao(dataset_two)
        
        # ek hi figure me do plots
        
        fig_canvas, (pllott_left, pllott_right) = plt.subplots(1, 2, figsize=(14, 6))
        
        pllott_left.plot(k1, inertia1, marker='o', linestyle='-', color='b')
        pllott_left.axvline(x=best_k1, color='r', linestyle='--',
                          label=f'optimal k={best_k1}')
        
        pllott_left.set_title("dataset 1 - kmeans objective")
        pllott_left.set_xlabel("number of clusters (k)")
        pllott_left.set_ylabel("objective value (inertia)")
        
        pllott_left.legend()
        pllott_left.grid(True, linestyle='--', alpha=0.6)
        
        
        pllott_right.plot(k2, inertia2, marker='o', linestyle='-', color='b')
        pllott_right.axvline(x=best_k2, color='r', linestyle='--',
                           label=f'optimal k={best_k2}')
        
        pllott_right.set_title("dataset 2 - kmeans objective")
        pllott_right.set_xlabel("number of clusters (k)")
        pllott_right.set_ylabel("objective value (inertia)")
        
        pllott_right.legend()
        pllott_right.grid(True, linestyle='--', alpha=0.6)
        
        
        plt.tight_layout()
        plt.savefig('plot.png')
        
        # sirf requested dataset ka best k print
        if str(target_dataset) == '1':
            print(best_k1)
        else:
            print(best_k2)


if __name__ == "__main__":
    main()